Poliza360/Models/ErrorViewModel.cs
namespace Poliza360.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Poliza360/Controllers/BeneficiariosController.cs
using Microsoft.AspNetCore.Mvc;

namespace Poliza360.Controllers
{
    public class BeneficiariosController : Controller
    {
        public IActionResult BeneficiariosView()
        {
            return View();
        }
    }
}

Poliza360/Controllers/GrupoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Poliza360.Controllers
{
    public class GrupoController : Controller
    {
        public IActionResult GrupoView()
        {
            return View();
        }
    }
}

Poliza360/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Poliza360.Models;

namespace Poliza360.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult PolizaView()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Poliza360/Controllers/ReglasController.cs
using Microsoft.AspNetCore.Mvc;

namespace Poliza360.Controllers
{
    public class ReglasController : Controller
    {
        public IActionResult ReglasView()
        {
            return View();
        }
    }
}

Poliza360/Views/Beneficiarios/BeneficiariosView.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <!--    Stylesheets    -->
    <link rel="stylesheet" href="https://cdn.grapecity.com/wijmo/5.20242.30/styles/wijmo.min.css">
    <style>
        .wj-inputnumber {
            width: 10em;
        }

        .params > div {
            margin-bottom: 0.5em;
        }
    </style>

</head>

<body>
    <!--    Main Content    -->
    <div class="row">
        <!-- Contenido    -->
        <main class="col-md-12 px-md-4 main-content">
            <h3 class="border-bottom mb-5">Beneficiarios</h3>

            <div class="container-fluid">
                <div class="form-group">
                    <label for="theInputDateRange">InputDateRange: </label>
                        <input id="theInputDateRange">
                </div>

            </div>
        </main>
    </div>

    <!--    JavaScripts    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.culture.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.input.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.filter.min.js"></script>
    <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.cellmaker.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.21.5/system.src.js" integrity="sha512-skZbMyvYdNoZfLmiGn5ii6KmklM82rYX2uWctBhzaXPxJgiv4XBwJnFGr5k8s+6tE1pcR1nuTKghozJHyzMcoA==" crossorigin="anonymous"></script>

    <script>
        const inputDateRange = new wijmo.input.InputDateRange('#theInputDateRange', {
            alwaysShowCalendar: true,
            predefinedRanges: getPredefinedRanges(),
            value: new Date(),
            rangeEnd: wijmo.DateTime.addDays(new Date(), 2),
            closeOnSelection: true,
            handleWheel: false,
            monthCount: 2,
            weeksBefore: 0,
            weeksAfter: 0,
        });
        //
        // init monthCount input
        let monthCount = new InputNumber('#monthCount', {
            min: 1,
            step: 1,
            value: inputDateRange.monthCount,
            valueChanged: (sender) => {
                inputDateRange.monthCount = sender.value;
            }
        });
        //
        // init weeksBefore input
        let weeksBefore = new InputNumber('#weeksBefore', {
            min: 0,
            step: 1,
            value: inputDateRange.weeksBefore,
            valueChanged: (sender) => {
                inputDateRange.weeksBefore = sender.value;
            }
        });
        //
        // init weeksAfter input
        let weeksAfter = new InputNumber('#weeksAfter', {
            min: 0,
            step: 1,
            value: inputDateRange.weeksAfter,
            valueChanged: (sender) => {
                inputDateRange.weeksAfter = sender.value;
            }
        });
        //
        // get predefined date ranges
        function getPredefinedRanges() {
            let dt = wijmo.DateTime, now = new Date();
            return {
                // custom
                'Custom Range': null,
                // days
                //'Today': [now, now],
                //'Yesterday': [dt.addDays(now, -1), dt.addDays(now, -1)],
                //'Tomorrow': [dt.addDays(now, +1), dt.addDays(now, +1)],
                // weeks
                'This Week': [dt.weekFirst(now), dt.weekLast(now)],
                'Last Week': [dt.weekFirst(dt.addDays(now, -7)), dt.weekLast(dt.addDays(now, -7))],
                'Next Week': [dt.weekFirst(dt.addDays(now, +7)), dt.weekLast(dt.addDays(now, +7))],
                // months
                'This Month': [dt.monthFirst(now), dt.monthLast(now)],
                'Last Month': [dt.monthFirst(dt.addMonths(now, -1)), dt.monthLast(dt.addMonths(now, -1))],
                'Next Month': [dt.monthFirst(dt.addMonths(now, +1)), dt.monthLast(dt.addMonths(now, +1))],
                // years
                'This Year': [dt.yearFirst(now), dt.yearLast(now)],
                'Last Year': [dt.addYears(dt.yearFirst(now), -1), dt.addYears(dt.yearLast(now), -1)],
                'Next Year': [dt.addYears(dt.yearFirst(now), +1), dt.addYears(dt.yearLast(now), +1)],
            };
        }
    </script>

</body>
</html>

Poliza360/Views/Grupo/GrupoView.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <!--    Stylesheets    -->
    <link rel="stylesheet" href="https://cdn.grapecity.com/wijmo/5.20242.30/styles/wijmo.min.css">
</head>

<body>
    <!--    Main Content    -->
    <div class="row">
        <!-- Contenido    -->
        <main class="col-md-12 px-md-4 main-content">
            <h3 class="border-bottom mb-5">Grupo</h3>
            <div>Hola</div>
        </main>
    </div>

    <!--    JavaScripts    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>

Poliza360/Views/Home/PolizaView.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <!--    Stylesheets    -->
        <link rel="stylesheet" href="https://cdn.grapecity.com/wijmo/5.20242.30/styles/wijmo.min.css">
        <style>
            .sidebar {
                width: 220px; 
                height: 100vh; 
                position: fixed; 
                overflow-y: auto; 
                right: 0; 
                top: 60px; 
                background-color: #ffffff; 
                overflow: visible !important;
            }

            .wj-popup-container {
                position: fixed !important;
                z-index: 1000;
                transform: translateX(-50%); /* Centra horizontalmente */
            }

            #dtRange {
                position: relative;
            }

            .showed {
                display: block;
                opacity: 1;
                transition: opacity 0.3s ease-in-out;
            }

            .hidden {
                display: none;
                opacity: 0;
                transition: opacity 0.3s ease-in-out;
            }

            @@media (max-width: 767.98px) {
                    .sidebar
                {
                    width: 100%; /* Navbar ocupa todo el ancho en móviles */
                    height: auto; 
                    position: static; /* No fijar en móviles */
                }

                main {
                    margin-right: 0; /* Sin margen en móviles */
                }
            }

            #btnAceptar{
                background-color: #3498db;
                color: #fff;
                border: none;
                padding: 0.5rem 1rem;
                border-radius: 5px;
                cursor: pointer;
                transition: box-shadow 0.5s ease;
            }
                #btnAceptar:hover {
                    background-color: #2471a3;
                    font-weight: bolder !important;
                    box-shadow: 0 8px 20px rgba(52, 152, 219, 0.4);
                }

            #navFormulario {
            border-left: 2px solid #cbd0dd; /* Color azul */
                height: 100vh; /* Altura completa */
                box-sizing: border-box; /* Evita desbordamiento */
            }
        </style>
    </head>

    <body>
        <!--    Main Content    -->
        <div class="row">
            <!-- Contenido    -->
            <main class="col-md-9 col-lg-10 px-md-4 main-content">
                <h3 class="border-bottom mb-5">Pólizas</h3>
                <div id="gridPoliza"></div>
            </main>

            <!-- Navbar Vertical -->
            <nav class="col-md-3 col-lg-2 sidebar order-last order-md-first bg-darker" id="navFormulario">
                <div class="position-sticky pt-3 navbar-darker">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <p class="navbar-vertical-label">FORMULARIO</p>
                            <div id="cmbFormulario"></div>

                            <div class="hidden mt-2" id="iptEmpleado1">
                                <input type="text" class="form-control" id="iptEmpleado1" placeholder="Empleado Inicial">
                            </div>

                            <div class="hidden mt-1 mb-3" id="iptEmpleado2">
                                <input type="text" class="form-control" id="iptEmpleado2" placeholder="Empleado Final">
                            </div>

                            <div class="hidden mt-2 mb-3" id="divCmbEmpleado3">
                                <div id="cmbEmpleado3"></div>
                            </div>

                            <div class="hidden mt-2 mb-3" id="divCmbEmpleado4">
                                <div id="cmbEmpleado4"></div>
                                <a asp-action="GrupoView" asp-controller="Grupo" class="nav-link"></a>
                            </div>

                            <p class="navbar-vertical-label">* Razón Social</p>
                            <div class="mb-3">
                                <input type="text" class="form-control" id="iptRazonSocial" placeholder="Razon Social">
                            </div>

                            <p class="navbar-vertical-label">* Grupo</p>
                            <div class="mb-3">
                                <div id="cmbGrupo"></div>
                            </div>

                            <div class="mb-3">
                                <input type="text" class="form-control" id="iptPoliza" placeholder="No. Poliza">
                            </div>

                            <p class="navbar-vertical-label">* Vigencia Póliza</p>
                            <div class="mb-3">
                                <div id="dtRange" class="flex-grow-1"></div>
                            </div>

                            <p class="navbar-vertical-label">* Regla</p>
                            <div class="mb-3">
                                <div id="cmbRegla"></div>
                            </div>

                            <div class="mb-3">
                                <input type="text" class="form-control" id="iptLugar" placeholder="Lugar">
                            </div>

                            <div class="mb-3">
                                <input type="text" class="form-control" id="iptContratante" placeholder="Contratante">
                            </div>

                            <div class="mb-3">
                                <button class="form-control" id="btnAceptar">Aceptar</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <!--    JavaScripts    -->
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.min.js"></script>
        <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.input.min.js"></script>
        <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.min.js"></script>
        <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.filter.min.js"></script>
        <script src="https://cdn.grapecity.com/wijmo/5.20242.30/controls/wijmo.grid.cellmaker.min.js"></script>

        <script>
            var dtRange = new wijmo.input.InputDate('#dtRange', {
                placeholder: 'Selecciona una fecha',
            });

            var gridPoliza = new wijmo.grid.FlexGrid('#gridPoliza', {
                autoGenerateColumns: false,
                headersVisibility: 'Column',
                columns: [
                    { binding: 'idEntrada_Salida', header: 'Id', width: 50 },
                    { binding: 'folio', header: 'Folio', width: 100 },
                    { binding: 'carro', header: 'Carro', width: 150 },
                    { binding: 'fechaEntrada', header: 'Fecha Entrada', width: '*' },
                    { binding: 'fechaSalida', header: 'Fecha Salida', width: '*' },
                ],
                itemsSource: [
                    { idEntrada_Salida: 1, folio: 'F001', carro: 'Carro1', fechaEntrada: '2025-02-11', fechaSalida: '2025-02-11' },
                    { idEntrada_Salida: 2, folio: 'F002', carro: 'Carro2', fechaEntrada: '2025-02-12', fechaSalida: '2025-02-12' },
                    { idEntrada_Salida: 3, folio: 'F003', carro: 'Carro3', fechaEntrada: '2025-02-13', fechaSalida: '2025-02-13' }
                ],
                isReadOnly: true
            });

            const $inputs = {
                empleado1: $("#iptEmpleado1"),
                empleado2: $("#iptEmpleado2"),
                empleado3: $("#divCmbEmpleado3"),
                empleado4: $("#divCmbEmpleado4"),
                empleado5: $("#cmbGrupo"),
                empleado6: $("#cmbRegla"),
            };

            const FORM_OPTIONS = [
                { Option: 'Empleado' },
                { Option: 'Centro de costos' },
                { Option: 'Grupos' },
            ];

            const CC_OPTIONS = [
                { OptionCC: 'CC1' },
                { OptionCC: 'CC2' },
                { OptionCC: 'CC3' },
            ];

            const GROUP_OPTIONS = [
                { OptionG: 'Grupo 1' },
                { OptionG: 'Grupo 2' },
                { OptionG: 'Grupo 3' },
            ];

            const RULE_OPTIONS = [
                { OptionR: 'Regla 1' },
                { OptionR: 'Regla 2' },
                { OptionR: 'Regla 3' },
            ];

            const toggleVisibility = (showEmpleados, showCC, showG) => {
                // Animación empleados 1 y 2
                if(showEmpleados) {
                    $inputs.empleado1.add($inputs.empleado2).stop(true, true).fadeIn(500)
                        .removeClass('hidden').addClass('showed');
                } else {
                    $inputs.empleado1.add($inputs.empleado2).stop(true, true).fadeOut(400)
                        .removeClass('showed').addClass('hidden');
                }

                if(showCC) {
                    $inputs.empleado3.stop(true, true).fadeIn(500)
                        .removeClass('hidden').addClass('showed');
                } else {
                    $inputs.empleado3.stop(true, true).fadeOut(400)
                        .removeClass('showed').addClass('hidden');
                }

                if(showG) {
                    redirigirView();
                    $inputs.empleado4.stop(true, true).fadeIn(500)
                        .removeClass('hidden').addClass('showed');
                    
                } else {
                    $inputs.empleado4.stop(true, true).fadeOut(400)
                        .removeClass('showed').addClass('hidden');
                }
            };

            const cmbEmpleado3 = new wijmo.input.AutoComplete('#cmbEmpleado3', {
                displayMemberPath: 'OptionCC',
                itemsSource: CC_OPTIONS
            });

            const CmbEmpleado4 = new wijmo.input.AutoComplete('#cmbEmpleado4', {
                displayMemberPath: 'OptionG',
                itemsSource: GROUP_OPTIONS
            });

            const cmbGrupo = new wijmo.input.AutoComplete('#cmbGrupo', {
                displayMemberPath: 'OptionG',
                itemsSource: GROUP_OPTIONS
            });

            const cmbRule = new wijmo.input.AutoComplete('#cmbRegla', {
                displayMemberPath: 'OptionR',
                itemsSource: RULE_OPTIONS
            });

            const cmbFormulario = new wijmo.input.AutoComplete('#cmbFormulario', {
                displayMemberPath: 'Option',
                itemsSource: FORM_OPTIONS,
                textChanged: sender => {
                    const option = sender.selectedItem?.Option;
                    toggleVisibility(option === 'Empleado', option === 'Centro de costos', option === 'Grupos');
                }
            });

            setTimeout(() => {
                cmbFormulario.selectedIndex = 0;
                cmbFormulario.textChanged.raise(cmbFormulario); // Forzar actualización
            }, 100);

            function redirigirView(){
                const polizaUrl = '@Url.Action("GrupoView", "Grupo")';
                window.location.href = polizaUrl;
            };
        </script>
    </body>
</html>

Poliza360/Views/Reglas/ReglasView.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <!--    Stylesheets    -->
    <link rel="stylesheet" href="https://cdn.grapecity.com/wijmo/5.20242.30/styles/wijmo.min.css">
</head>

<body>
    <!--    Main Content    -->
    <div class="row">
        <!-- Contenido    -->
        <main class="col-md-12 px-md-4 main-content">
            <h3 class="border-bottom mb-5">Reglas</h3>
            <div>Hola</div>
        </main>
    </div>

    <!--    JavaScripts    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>